// Controles rond de release-badge: gestempelde versie, onbekende versie en de releasehistorie.
module.exports = async function releaseBadge({ assert, flush, byIdMap, fetchCalls, initialBadge, setFetchMode, stappen }) {
  await flush(); await flush();
  assert(initialBadge === "release: onbekend", "badge heeft een veilige beginwaarde vóór de fetch-response");
  assert(byIdMap["release-badge-label"].textContent === "release: v9.9.9 +2 · abc1234", "badge toont de gestempelde versie, commits-ahead en sha");
  assert(byIdMap["release-current-link"].textContent.includes("v9.9.9"), "badge-link toont de actieve versie");
  assert(byIdMap["release-current-link"].href.endsWith("/v9.9.9"), "badge-link verwijst naar de actieve release");
  assert(fetchCalls.includes("version.json"), "badge vraagt buildinformatie op via fetch");
  assert(byIdMap["release-history"].classList.contains("release-badge") && byIdMap["release-history"].classList.contains("dev"), "badge krijgt de ontwikkelstatus in de DOM");
  assert(byIdMap["release-history"].open !== true, "gesloten releaseknop houdt de extra deploymentinformatie uit beeld");
  setFetchMode("invalid");
  stappen.opnieuw(); await flush(); await flush();
  assert(byIdMap["release-badge-label"].textContent === "release: tijdelijk niet beschikbaar", "ongeldig version.json toont tijdelijk niet beschikbaar");
  assert(byIdMap["release-current-link"].href.endsWith("/releases"), "ongeldige versie linkt naar het releaseoverzicht");
  setFetchMode("missing");
  const callsBeforeMissing = fetchCalls.length;
  stappen.opnieuw(); await flush(); await flush();
  assert(byIdMap["release-badge-label"].textContent === "release: versie onbekend", "ontbrekend version.json toont versie onbekend");
  assert(byIdMap["release-current-link"].href.endsWith("/releases"), "onbekende versie linkt naar het releaseoverzicht");
  assert(fetchCalls.slice(callsBeforeMissing).every(url => url === "version.json"), "ontbrekend version.json doet geen GitHub-fetch");
  setFetchMode("version");
  stappen.opnieuw(); await flush(); await flush();
  assert(byIdMap["release-badge-label"].textContent.startsWith("release: v9.9.9"), "badge kan na fallback opnieuw een version-file gebruiken");
  setFetchMode("history");
  byIdMap["release-history"].open = true;
  byIdMap["release-history"].dataset.historyLoaded = "false";
  byIdMap["release-history"].ontoggle(); await flush(); await flush();
  assert(byIdMap["release-history-list"].children.length === 2, "releasehistorie rendert alle ontvangen items");
  assert(byIdMap["release-history"].open === true, "geopende releaseknop toont het uitgebreide releasepaneel");
  const historyLink = byIdMap["release-history-list"].children[0].children[0];
  assert(historyLink.textContent === "v9.9.8", "releasehistorie toont tagnaam");
  assert(historyLink.href === "https://example.test/releases/v9.9.8" && historyLink.target === "_blank", "releasehistorie-item linkt naar release-notes in nieuw tabblad");
  assert(byIdMap["release-history-list"].children[0].children[1].textContent.length > 0, "releasehistorie toont publicatiedatum");
  setFetchMode("error");
  byIdMap["release-history"].dataset.historyLoaded = "false";
  byIdMap["release-history"].ontoggle(); await flush(); await flush();
  assert(byIdMap["release-history-list"].children[0]._html.indexOf("Geen eerdere releases") >= 0, "releasehistorie toont een foutveilige lege toestand");
  stappen.opnieuw(); await flush(); await flush();
  assert(!byIdMap["release-badge-label"].textContent.includes("onbekend") && byIdMap["release-badge-label"].textContent.includes("tijdelijk niet beschikbaar"), "badge toont een begrijpelijke toestand als GitHub niet bereikbaar is");
};
